[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/pi-approve"
  to   = "/.netlify/functions/pi-approve"
  status = 200

[[redirects]]
  from = "/api/pi-complete"
  to   = "/.netlify/functions/pi-complete"
  status = 200

[[redirects]]
  from = "/api/pi-me"
  to   = "/.netlify/functions/pi-me"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *"
